version: "3"
services:
  web:
    ports:
      - "3000:3000"
    build: ./frontend-cloud-app
  app:
    build: ./app
    links:
      - db
    ports:
      - "4999:4999"
    depends_on:
      - db

  db:
    # platform: linux/x86_64
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "32000:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql
